import {ScaledSheet} from 'react-native-size-matters/extend';

const StylesDetails = ScaledSheet.create({
  V: {
    flex: 1,
    padding: '20@s',
    backgroundColor: '#FFFFFFFF',
  },
  V3: {
    backgroundColor: '#ECECEC',
    borderRadius: 8,
    padding: '10@s',
    borderColor: '#373737',
    shadowColor: '#373737',
    elevation: 4,
  },
  V43: {
    backgroundColor: '#ECECEC',
    borderRadius: 8,
    padding: '10@s',
    borderColor: '#373737',
    shadowColor: '#373737',
    elevation: 4,
  },
  logop1: {
    width: '20@s',
    height: '20@s',
    left: '-83@s',
  },
  V4: {
    backgroundColor: '#ECECEC',
    borderRadius: 8,
    padding: '20@s',
    alignSelf: 'flex-start',
  },
  V8: {
    backgroundColor: '#268C63',
    borderRadius: 9.5,
    padding: '0@s',
    width: '59@s',
    height: '14@s',
    top: -40,
  },
  V9: {
    backgroundColor: '#268C63',
    borderRadius: 30,
    padding: '10@s',
    width: '22@s',
    height: '22@s',
    top: '-49@s',
    left: '0@s',
  },
  V5: {
    backgroundColor: '#ECECEC',
    borderRadius: 8,
    padding: '20@s',
    alignSelf: 'flex-end',
    top: '-69@mvs',
  },
  Tel33: {
    color: '#373737',
    fontWeight: '600',
    fontSize: 20,
    left: 22,
  },
  Tel32: {
    color: '#373737',
    fontWeight: '600',
    fontSize: 20,
    left: -20,
  },
  Tel2: {
    color: '#373737',
    fontWeight: '600',
    fontSize: 20,
    left: 10,
  },

  Tel09: {
    color: '#373737',
    fontWeight: '600',
    fontSize: 20,
    left: 30,
    width: '100@s',
    alignItems: 'center',
  },
  Tel08: {
    color: '#373737',
    fontWeight: '600',
    fontSize: 20,
    left: '0@s',
    width: '80@s',
    alignItems: 'center',
  },
  Tel5: {
    fontWeight: '500',
    fontSize: 18,
    color: '#373737',
  },
  Tel6: {
    fontWeight: '500',
    fontSize: 18,
    color: '#373737',
    top: -45,
    left: -8,
  },
  Btn: {
    backgroundColor: '#268C63',
    color: '#FFF',
    fontSize: 30,
    fontWeight: 'bold',
    textAlign: 'center',
    padding: '6@s',
    borderRadius: '8@s',
    marginVertical: '10@s',
    top: '-60@s',
  },
  Tel3: {
    color: '#AAAAAA',
    fontSize: 18,
    alignSelf: 'flex-end',
    marginVertical: '5@s',
  },
  Vp: {
    width: 397.5,
    height: 200,
    backgroundColor: '#ECECEC',
    alignContent: 'center',
    alignItems: 'center',
  },
});
export default StylesDetails;
